# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('store', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('code', models.IntegerField()),
                ('salerProductName', models.CharField(max_length=50)),
                ('mainGroup', models.CharField(max_length=50)),
                ('subGroup', models.CharField(max_length=50)),
                ('productVariety', models.CharField(max_length=50)),
                ('salesAmount', models.IntegerField()),
            ],
        ),
    ]
